version: '3'

services:
  redis:
    image: redis:alpine
    command: ["redis-server","--appendonly yes"]    
    # command: ["redis-server","--appendonly yes","--requirepass pwd"]    
    ports:
      - 6379:6379
      - 16379:16379    
    networks:
      - redisnet
    volumes:
      - redis-data:/data

networks:
 redisnet:    
    
volumes:
  redis-data:    
    